Update socket.yml

diff --git a/.github/workflows/socket.yml b/.github/workflows/socket.yml
--- a/.github/workflows/socket.yml
+++ b/.github/workflows/socket.yml
@@ -29,9 +29,19 @@ jobs:
       - name: Install Dependencies
         run: pip install socketsecurity --upgrade
 
+      - name: Ensure GitHub API Token is Set
+        run: |
+          if [ -z "${{ secrets.GITHUB_TOKEN }}" ]; then
+            echo "Error: GITHUB_TOKEN is not set."
+            exit 1
+          else
+            echo "GitHub token is available."
+          fi
+
       - name: Run Socket CLI
         env:
           SOCKET_SECURITY_API_KEY: ${{ secrets.SOCKET_SECURITY_API_KEY }}
+          GH_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           # Sanitize repository name for CLI
           REPO_NAME=$(basename $GITHUB_REPOSITORY | tr -d '.')
