Update socket.yml

diff --git a/.github/workflows/socket.yml b/.github/workflows/socket.yml
--- a/.github/workflows/socket.yml
+++ b/.github/workflows/socket.yml
@@ -57,7 +57,7 @@ jobs:
           GH_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           echo "Running Socket CLI..."
-          set -x
+          set -x  # Enable detailed command logging
           socketcli --scm github \
             --repo ${{ github.event.repository.name }} \
             --branch "${{ env.REF_NAME }}" \
@@ -82,7 +82,7 @@ jobs:
             exit 1
           fi
 
-      - name: Generate SARIF
+      - name: Convert Results to SARIF
         run: |
           echo "Converting results to SARIF..."
           if [ -s socket_results.json ]; then
@@ -90,12 +90,20 @@ jobs:
               --socket_results "socket_results.json" \
               --output_file "socket_results.sarif"
           elif [ -s sbom.json ]; then
-            echo "Generating SARIF from sbom.json..."
             python socket_sarif.py \
               --socket_results "sbom.json" \
               --output_file "socket_results.sarif"
           else
             echo "No valid data to generate SARIF."
+            exit 1
+
+      - name: Debug SARIF File
+        run: |
+          echo "Debugging SARIF file..."
+          if [ -s socket_results.sarif ]; then
+            cat socket_results.sarif
+          else
+            echo "Error: socket_results.sarif is missing or empty."
             exit 1
 
       - name: Upload SARIF Results
