Update socket.yml

diff --git a/.github/workflows/socket.yml b/.github/workflows/socket.yml
--- a/.github/workflows/socket.yml
+++ b/.github/workflows/socket.yml
@@ -39,21 +39,33 @@ jobs:
           echo "Event Name: ${{ github.event_name }}"
           echo "Branch Name: ${{ env.REF_NAME }}"
           echo "PR Number: ${{ env.PR_NUMBER }}"
+          echo "Checking for GH_API_TOKEN..."
+          if [ -z "${{ secrets.GITHUB_TOKEN }}" ]; then
+            echo "Error: GITHUB_TOKEN is not available!"
+            exit 1
+          else
+            echo "GITHUB_TOKEN is available."
+          fi
 
       - name: Run Socket Scan
         env:
           SOCKET_SECURITY_API_KEY: ${{ secrets.SOCKET_SECURITY_API_KEY }}
+          GH_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
+          echo "Running Socket CLI..."
+          set -x  # Enable command logging for debug
           socketcli --scm github \
             --repo ${{ github.event.repository.name }} \
             --branch "${{ env.REF_NAME }}" \
             --pr_number "${{ env.PR_NUMBER }}" \
+            --api_token "${{ secrets.GITHUB_TOKEN }}" \
             --enable-json \
             --sbom-file "sbom.json" \
             --committer "$GITHUB_ACTOR" \
             --commit_message "${{ github.event.head_commit.message }}" \
             --target_path $GITHUB_WORKSPACE || {
-              echo "Socket CLI failed."; exit 1;
+              echo "Socket CLI failed.";
+              exit 1;
             }
 
       - name: Validate Socket Results
