Update socket.yml

diff --git a/.github/workflows/socket.yml b/.github/workflows/socket.yml
--- a/.github/workflows/socket.yml
+++ b/.github/workflows/socket.yml
@@ -1,17 +1,20 @@
-name: socket-security-workflow
-on: 
+name: Socket Security Workflow
+run-name: Socket Security GitHub Action
+
+on:
   push:
     branches:
       - main
   pull_request:
     branches:
       - main
+  schedule:
+    - cron: '0 0 * * *'
 
 jobs:
   socket-security:
     permissions:
       contents: read
-      pull-requests: write
       security-events: write
     runs-on: ubuntu-latest
     steps:
@@ -21,7 +24,7 @@ jobs:
       - name: Set up Python
         uses: actions/setup-python@v5
         with:
-          python-version: "3.12"
+          python-version: '3.12'
 
       - name: Install Dependencies
         run: pip install socketsecurity --upgrade
@@ -29,15 +32,27 @@ jobs:
       - name: Run Socket CLI
         env:
           SOCKET_SECURITY_API_KEY: ${{ secrets.SOCKET_SECURITY_API_KEY }}
-          GH_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
+          # Sanitize repository name for CLI
+          REPO_NAME=$(basename $GITHUB_REPOSITORY | tr -d '.')
+          ORG_NAME=$(dirname $GITHUB_REPOSITORY)
+          SANITIZED_REPO="$ORG_NAME/$REPO_NAME"
+
+          echo "Sanitized repo slug: $SANITIZED_REPO"
+
+          # Run CLI
           socketcli --scm github \
-            --repo ${{ github.repository }} \
+            --repo "$SANITIZED_REPO" \
             --branch "${{ github.ref_name }}" \
             --pr_number "${{ github.event.pull_request.number || 0 }}" \
             --enable-json \
             --sbom-file "sbom.json" \
             --target_path $GITHUB_WORKSPACE > socket_results.json || echo "Socket CLI failed."
+
+      - name: Debugging CLI Results
+        run: |
+          echo "CLI results in socket_results.json:"
+          cat socket_results.json || echo "socket_results.json is empty or missing."
 
       - name: Convert Results to SARIF
         run: |
