Update socket.yml

diff --git a/.github/workflows/socket.yml b/.github/workflows/socket.yml
--- a/.github/workflows/socket.yml
+++ b/.github/workflows/socket.yml
@@ -28,6 +28,7 @@ jobs:
       - name: Run Socket CLI
         env:
           SOCKET_SECURITY_API_KEY: ${{ secrets.SOCKET_SECURITY_API_KEY }}
+          GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
         run: |
           echo "Running Socket CLI with debug mode enabled..."
           set -x
@@ -44,29 +45,41 @@ jobs:
               echo "Socket CLI failed but data might still be available.";
             }
 
-      - name: Wait for CLI to Complete
+      - name: Sleep for File Generation
         run: sleep 10
 
-      - name: Validate Results
+      - name: Check File Existence
         run: |
           echo "Validating CLI output..."
-          if [ -s socket_results.json ]; then
-            echo "Using socket_results.json"
-            RESULT_FILE="socket_results.json"
-          elif [ -s sbom.json ]; then
-            echo "Using sbom.json"
-            RESULT_FILE="sbom.json"
+          if [ -f "socket_results.json" ]; then
+            echo "socket_results.json found."
+            cat socket_results.json
           else
-            echo "Error: Both socket_results.json and sbom.json are missing or empty."
-            exit 1
+            echo "Error: socket_results.json is missing."
           fi
-          echo "RESULT_FILE=$RESULT_FILE" >> $GITHUB_ENV
+
+          if [ -f "sbom.json" ]; then
+            echo "sbom.json found."
+            cat sbom.json
+          else
+            echo "Error: sbom.json is missing."
+          fi
 
       - name: Convert Results to SARIF
         run: |
-          python socket_sarif.py \
-            --socket_results "${{ env.RESULT_FILE }}" \
-            --output_file "socket_results.sarif"
+          if [ -s socket_results.json ]; then
+            echo "Using socket_results.json"
+            python socket_sarif.py \
+              --socket_results "socket_results.json" \
+              --output_file "socket_results.sarif"
+          elif [ -s sbom.json ]; then
+            echo "Using sbom.json"
+            python socket_sarif.py \
+              --socket_results "sbom.json" \
+              --output_file "socket_results.sarif"
+          else
+            echo "Error: Both socket_results.json and sbom.json are missing or empty."
+            exit 1
 
       - name: Upload SARIF to GitHub
         uses: github/codeql-action/upload-sarif@v3
