Update socket.yml

diff --git a/.github/workflows/socket.yml b/.github/workflows/socket.yml
--- a/.github/workflows/socket.yml
+++ b/.github/workflows/socket.yml
@@ -1,7 +1,7 @@
 name: socket-security-workflow
-run-name: Socket Security Github Action
+run-name: Socket Security GitHub Action
 
-on: 
+on:
   push:
     branches:
       - main
@@ -33,56 +33,40 @@ jobs:
       - name: Install Dependencies
         run: pip install socketsecurity --upgrade
 
-      - name: Get PR State
-        if: github.event_name == 'pull_request'
-        run: echo "EVENT_ACTION=${{ github.event.action }}" >> $GITHUB_ENV
-
-      - name: Check if Default Branch
-        if: ${{ always() && format('refs/heads/{0}', github.event.repository.default_branch) == github.ref }}
-        run: echo "DEFAULT_BRANCH=1" >> $GITHUB_ENV
-
-      - uses: actions/github-script@v7
-        id: get_pr_data
-        with:
-          script: |
-              let data = (
-                await github.rest.repos.listPullRequestsAssociatedWithCommit({
-                  commit_sha: context.sha,
-                  owner: context.repo.owner,
-                  repo: context.repo.repo,
-                })
-              ).data[0];
-              if (data === undefined) {
-                data = {
-                  'number': null,
-                  'title': null
-                }
-              }
-              
-              return data;
-
-      - name: Save Pull Request Number
+      - name: Detect Changed Files
+        id: changed-files
         run: |
-          echo "PR_NUMBER=${{ fromJson(steps.get_pr_data.outputs.result).number || github.event.issue.number || github.event.number }}" >> $GITHUB_ENV
+          if ${{ github.event_name == 'pull_request' }}; then
+              echo "changed_files=$(git diff --name-only -r HEAD^1 HEAD | xargs)" >> $GITHUB_OUTPUT
+          else
+              echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)" >> $GITHUB_OUTPUT
+          fi
 
       - name: Run Socket Scan
         env:
           SOCKET_SECURITY_API_KEY: ${{ secrets.SOCKET_SECURITY_API_KEY }}
-          GH_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
         run: |
           socketcli --scm github \
             --repo ${{ github.event.repository.name }} \
             --branch "${{ github.ref_name }}" \
             $(if [ ! -z $DEFAULT_BRANCH ]; then echo "--default_branch"; fi) \
-            --pr_number $(if [ -z $PR_NUMBER ]; then echo 0; else echo $PR_NUMBER;fi) \
+            --enable-json \
+            --sbom-file \
             --committer "$GITHUB_ACTOR" \
-            --commit_message "$COMMIT_MESSAGE" \
+            --commit_message "${{ github.event.head_commit.message }}" \
             --target_path $GITHUB_WORKSPACE > socket_results.json
         continue-on-error: true
 
+      - name: Debug Socket Results
+        if: always()
+        run: cat socket_results.json || echo "socket_results.json does not exist or is empty."
+
       - name: Convert Socket Results to SARIF
         run: |
+          if [ ! -s socket_results.json ]; then
+            echo "Error: socket_results.json is empty or missing."
+            exit 1
+          fi
           python socket_sarif.py \
             --socket_results "socket_results.json" \
             --output_file "socket_results.sarif"
